## Fundamentals

Day 1 - [What is DLL search order and how it enables red team trade-craft?](https://www.100daysofredteam.com/p/what-is-dll-search-order-and-how)  
Day 2 - [The origin of session sharing in C2 infrastructure](https://www.100daysofredteam.com/p/the-origin-of-session-sharing-in)  
Day 3 - [What is COM Hijacking and how it enables red team trade-craft?](https://www.100daysofredteam.com/p/what-is-com-hijacking)  
Day 4 - [Do you have AtomBombing in your red team arsenal?](https://www.100daysofredteam.com/p/atombombing-in-your-red-team-arsenal)  
Day 5 - [Can your red team live off the land?](https://www.100daysofredteam.com/p/can-your-red-team-live-off-the-land)  
Day 6 - [What is a red team methodology?](https://www.100daysofredteam.com/p/what-is-a-red-team-methodology)  
Day 7 - [What is Process Hollowing and how it enables red team trade-craft?](https://www.100daysofredteam.com/p/what-is-process-hollowing)  
Day 8 - [What is Process Doppelgänging and how it enables red team trade-craft?](https://www.100daysofredteam.com/p/what-is-process-doppelganging)  
Day 9 - [Is a red team assessment same as a penetration test?](https://www.100daysofredteam.com/p/red-teaming-vs-penetration-testing)  
Day 10 - [Should a red team assessment be unannounced or announced?](https://www.100daysofredteam.com/p/unannounced-vs-announced-red-team-assessments)  
Day 11 - [What is Process Herpaderping and how it enables red team trade-craft?](https://www.100daysofredteam.com/p/what-is-process-herpaderping-red-team)  
Day 12 - [What is Process Ghosting and how it enables red team trade-craft?](https://www.100daysofredteam.com/p/what-is-process-ghosting)  
Day 13 - [What is situational awareness in the context of red team assessments?](https://www.100daysofredteam.com/p/what-is-situational-awareness-red-team)  
Day 14 - [Types of models for conducting red team engagements](https://www.100daysofredteam.com/p/types-of-models-red-team-engagements)  
Day 15 - [Debunking common myths around red teaming](https://www.100daysofredteam.com/p/debunking-common-myths-around-red-teaming)  
Day 16 - [How mature is your red team?](https://www.100daysofredteam.com/p/how-mature-is-your-red-team)  
Day 17 - [What is Process Reimaging and how it enables red team trade-craft?](https://www.100daysofredteam.com/p/what-is-process-reimaging)  
Day 18 - [What is Deconfliction in the context of a red team engagement?](https://www.100daysofredteam.com/p/what-is-deconfliction-process-in-red-teaming)  
Day 19 - [The different genres of red team assessments](https://www.100daysofredteam.com/p/the-different-genres-of-red-team-assessments)  
Day 20 - [Using Microsoft Teams to execute commands remotely - ConvoC2](https://www.100daysofredteam.com/p/using-microsoft-teams-to-execute-commands-remotely-convo-c2)  
Day 21 - [What is DLL Injection and how it enables red team trade-craft?](https://www.100daysofredteam.com/p/what-is-dll-injection-attack)  
Day 22 - [What is Reflective DLL Injection and how it enables red team trade-craft?](https://www.100daysofredteam.com/p/what-is-reflective-dll-injection)  
Day 23 - [The spectrum of cells in a red team engagement](https://www.100daysofredteam.com/p/the-spectrum-of-cells-in-a-red-team-engagement)  
Day 24 - [It's all about Command and Control](https://www.100daysofredteam.com/p/its-all-about-command-and-control)  
Day 25 - [In OPSEC the red team trusts](https://www.100daysofredteam.com/p/in-opsec-the-red-team-trusts)  
Day 26 - [Understanding C2 infrastructure - Part 1](https://www.100daysofredteam.com/p/understanding-c2-infrastructure-part-1)  
Day 27 - [Choose your own red team adventure by Tim MalcomVetter](https://www.100daysofredteam.com/p/choose-your-own-red-team-adventure-by-tim-malcomvetter)  
Day 28 - [Understanding C2 infrastructure - Part 2](https://www.100daysofredteam.com/p/understanding-c2-infrastructure-part-2)  
Day 29 - [Trusted Agent in red team engagements](https://www.100daysofredteam.com/p/trusted-agent-ta-in-red-team-engagements)  
Day 30 - [Threat profiling and decomposition for red team operations](https://www.100daysofredteam.com/p/threat-profiling-and-decomposition-for-red-team-ops)  
Day 31 - [The lifecycle of a red team engagement](https://www.100daysofredteam.com/p/the-lifecycle-of-a-red-team-engagement)  
Day 32 - [Using WDAC to Disable EDR - Krueger](https://www.100daysofredteam.com/p/using-wdac-to-disable-edr-krueger)  
Day 33 - [Counter-APT Red Teaming](https://www.100daysofredteam.com/p/counter-apt-red-teaming-reverse-red-teaming)  
Day 34 - [Data handling considerations for red team engagements](https://www.100daysofredteam.com/p/data-handling-considerations-for-red-team-engagements)  
Day 35 - [Understanding C2 infrastructure - Part 3](https://www.100daysofredteam.com/p/understanding-c2-infrastructure-part-3)  
Day 36 - [Fork & run and its drawbacks for red team tradecraft](https://www.100daysofredteam.com/p/fork-and-run-and-its-drawbacks-for-red-team-tradecraft)  
Day 37 - [What is Early Bird code injection and how it enables red team trade-craft?](https://www.100daysofredteam.com/p/what-is-early-bird-code-injection-red-team)  
Day 38 - [How to securely access your home red team lab from outside?](https://www.100daysofredteam.com/p/how-to-securely-access-your-home-red-team-lab-from-the-internet)  
Day 39 - [Scoping a red team engagement](https://www.100daysofredteam.com/p/scoping-a-red-team-engagement)  
Day 40 - [Navigating ethics in red teaming](https://www.100daysofredteam.com/p/navigating-ethics-in-red-teaming)  
Day 41 - [What is Process Hypnosis and how it enables red team trade-craft?](https://www.100daysofredteam.com/p/what-is-process-hypnosis-red-team)  
Day 42 - [What is Continuous Automated Red Teaming (CART)?](https://www.100daysofredteam.com/p/continuous-automated-red-teaming-cart)  
Day 43 - [Enhancing C2 agent via Beacon Object Files (BOF)](https://www.100daysofredteam.com/p/enhancing-c2-agent-via-beacon-object-files-bof)  
Day 44 - [Quick introduction to AMSI for red team professionals](https://www.100daysofredteam.com/p/quick-introduction-to-amsi-for-red-team)  
Day 45 - [Bypassing AMSI for red team tradecraft](https://www.100daysofredteam.com/p/bypassing-amsi-for-red-team-tradecraft)  
Day 46 - [What is dylib hijacking in macOS and how it enables red team trade-craft?](https://www.100daysofredteam.com/p/what-is-dylib-hijacking-in-macos)  
Day 47 - [Why Rules of Engagement matter in a red team assessment?](https://www.100daysofredteam.com/p/why-rules-of-engagement-matter-in-red-team-assessments)  
Day 48 - [What is Threadless Injection and how it enables red team trade-craft?](https://www.100daysofredteam.com/p/what-is-threadless-injection-red-team)  
Day 49 - [What is API hashing and how it enables red team trade-craft?](https://www.100daysofredteam.com/p/what-is-api-hashing-red-team)  
Day 50 - [Quick introduction to P/Invoke and D/Invoke for red team professionals](https://www.100daysofredteam.com/p/quick-introduction-to-pinvoke-and-dinvoke-red-team)  
Day 51 - [The Red Teamer's Guide to Responsibility and Accountability](https://www.100daysofredteam.com/p/the-red-teamers-guide-to-responsibility-and-accountability)  
Day 52 - [Install Havoc C2 on Ubuntu 22.04 (2025)](https://www.100daysofredteam.com/p/install-havoc-c2-on-ubuntu-2204-2025)  
Day 53 - [Choose Your Own (Pwn) Red Team Adventure by Matt Kiely](https://www.100daysofredteam.com/p/choose-your-own-pwn-red-team-adventure-by-matt-kiely)  
Day 54 - [Understanding C2 infrastructure - Part 4](https://www.100daysofredteam.com/p/understanding-c2-infrastructure-part-4)  
Day 55 - [macOS security fundamentals for red team professionals - Part 1](https://www.100daysofredteam.com/p/macos-security-for-red-team-professionals-part-1)  
Day 56 - [macOS security fundamentals for red team professionals - Part 2](https://www.100daysofredteam.com/p/macos-security-fundamentals-for-red-team-part-2)  
Day 57 - [macOS security fundamentals for red team professionals - Part 3](https://www.100daysofredteam.com/p/macos-security-fundamentals-for-red-team-part-3)  
Day 58 - [macOS security fundamentals for red team professionals - Part 4](https://www.100daysofredteam.com/p/macos-security-fundamentals-for-red-team-part-4)  
Day 59 - [A Red Teamer's Primer to Establishing Persistence on macOS](https://www.100daysofredteam.com/p/a-red-teamers-primer-to-establishing-persistence-on-macos)  
Day 60 - [macOS security fundamentals for red team professionals - Part 5](https://www.100daysofredteam.com/p/macos-security-fundamentals-for-red-team-part-5)  
Day 61 - [What is Dirty Vanity process injection and how it enables red team trade-craft?](https://www.100daysofredteam.com/p/what-is-dirty-vanity-process-injection-red-team)  
Day 62 - [Mach-O file format for red team professionals - Part 1](https://www.100daysofredteam.com/p/mach-o-file-format-for-red-team-part-1)  
Day 63 - [Mach-O file format for red team professionals - Part 2](https://www.100daysofredteam.com/p/mach-o-file-format-for-red-team-part-2)  
Day 64 - [Mach-O file format for red team professionals - Part 3](https://www.100daysofredteam.com/p/mach-o-file-format-for-red-team-part-3)  
Day 65 - [Mach-O file format for red team professionals - Part 4](https://www.100daysofredteam.com/p/mach-o-file-format-for-red-team-part-4)  
Day 66 - [Mach-O file format for red team professionals - Part 5](https://www.100daysofredteam.com/p/mach-o-file-format-for-red-team-part-5)  
Day 67 - [How to ensure that the red team is setup for success?](https://www.100daysofredteam.com/p/how-to-ensure-that-the-red-team-is-setup-for-success)  
Day 68 - [4 macOS payload packaging tools for red teams](https://www.100daysofredteam.com/p/4-macos-payload-packaging-tools-for-red-teams)  
Day 69 - [Quick introduction to Protected Processes and Protected Process Light for red team professionals](https://www.100daysofredteam.com/p/quick-introduction-to-protected-processes-protected-process-light-red-team)  
Day 70 - [Bypassing Protected Process Light for red team tradecraft](https://www.100daysofredteam.com/p/bypassing-protected-process-light-for-red-team-tradecraft)  
Day 71 - [Role of threat intelligence in a red team engagement](https://www.100daysofredteam.com/p/role-of-threat-intelligence-in-a-red-team-engagement)  
Day 72 - [Quick introduction to Windows Access Tokens for red team professionals](https://www.100daysofredteam.com/p/quick-introduction-to-windows-access-tokens-red-team)  
Day 73 - [Building a custom tool to enumerate Windows Access Tokens for red team tradecraft](https://www.100daysofredteam.com/p/building-a-custom-tool-to-enumerate-windows-access-tokens-red-team)  
Day 74 - [Navigating the Cobalt Strike Universe](https://www.100daysofredteam.com/p/navigating-the-cobalt-strike-universe)  
Day 75 - [Hunting high-value Windows Access Tokens using open-source tools](https://www.100daysofredteam.com/p/hunting-high-value-windows-access-tokens-using-open-source-tools)  
Day 76 - [TokenHeist: Stealing Windows Access Tokens for fun and education](https://www.100daysofredteam.com/p/tokenheist-stealing-windows-access-for-fun-and-education)  
Day 77 - [Performing a Token Heist without administrator rights](https://www.100daysofredteam.com/p/performing-a-token-heist-without-administrator-rights)  
Day 78 - [Quick introduction to User Access Control for red team professionals](https://www.100daysofredteam.com/p/quick-introduction-to-user-access-contol-red-team)  
Day 79 - [Common techniques to bypass UAC for red team trade-craft](https://www.100daysofredteam.com/p/common-techniques-to-bypass-uac-for-red-team-tradecraft)  
Day 80 - [Using Havoc C2 to bypass UAC](https://www.100daysofredteam.com/p/using-havoc-c2-to-bypass-uac)  
Day 81 - [Using Gen AI and Havoc C2 for anti-malware evasion](https://www.100daysofredteam.com/p/using-gen-ai-and-havoc-c2-for-anti-malware-evasion)  
Day 82 - [Use cases of large language models for red team trade-craft](https://www.100daysofredteam.com/p/use-cases-of-large-language-models-for-red-team)  
Day 83 - [Common Generative AI attacks and vulnerabilities for red team professionals](https://www.100daysofredteam.com/p/common-generative-ai-attacks-and-vulnerabilities-red-team)  
Day 84 - [Adversarial datasets to red team Generative AI models](https://www.100daysofredteam.com/p/adversarial-datasets-to-red-team-generative-ai-models)  
Day 85 - [Red Teaming Language Models with Language Models](https://www.100daysofredteam.com/p/red-teaming-language-models-with-language-models)  
Day 86 - [Using Havoc C2 to bypass UAC - Part 2](https://www.100daysofredteam.com/p/using-havoc-c2-to-bypass-part-2)  
Day 87 - [Creating a simple beacon object file for Havoc C2](https://www.100daysofredteam.com/p/creating-a-simple-beacon-object-file-for-havoc-c2)  
Day 88 - [Direct and indirect syscalls for red team operations](https://www.100daysofredteam.com/p/direct-and-indirect-syscalls-for-red-team-ops)  
Day 89 - [What is PPID spoofing and how it enables red team trade-craft?](https://www.100daysofredteam.com/p/what-is-ppid-spoofing-red-team)  
Day 90 - [Quick introduction to kernel callbacks for red team professionals](https://www.100daysofredteam.com/p/quick-introduction-to-kernel-callbacks-red-team)  
Day 91 - [Let's write a Beacon Object File for Havoc C2 - Part 1](https://www.100daysofredteam.com/p/lets-write-a-beacon-object-file-for-havoc-c2-part-1)  
Day 92 - [Let's write a Beacon Object File for Havoc C2 - Part 2](https://www.100daysofredteam.com/p/lets-write-a-beacon-object-file-for-havoc-c2-part-2)  
Day 93 - [Let's write a Beacon Object File for Havoc C2 - Part 3](https://www.100daysofredteam.com/p/lets-write-a-beacon-object-file-for-havoc-c2-part-3)  
Day 94 - [How process injection works in Linux vs Windows?](https://www.100daysofredteam.com/p/how-process-injection-works-in-linux-vs-windows)  
Day 95 - [Let's write a Beacon Object File for Havoc C2 - Part 4](https://www.100daysofredteam.com/p/lets-write-a-beacon-object-file-for-havoc-c2-part-4)  
Day 96 - [What is ptrace process injection and how it enables red team trade-craft?](https://www.100daysofredteam.com/p/what-is-ptrace-process-injection)  
Day 97 - [How quantum computing might shape red teaming?](https://www.100daysofredteam.com/p/how-quantum-computing-might-shape-red-teaming)  
Day 98 - [Communicating results of a red team engagement](https://www.100daysofredteam.com/p/communicating-results-of-a-red-team-engagement)  
Day 99 - [The Red Team Pyramid of Pain](https://www.100daysofredteam.com/p/the-red-team-pyramid-of-pain)  
Day 100 - [What is red teaming?](https://www.100daysofredteam.com/p/what-is-red-teaming)  
